# Generated by Django 5.2.4 on 2025-07-27 03:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Dream description')),
                ('voice_recording', models.FileField(blank=True, help_text='Voice recording of the dream', null=True, upload_to='dream_recordings/%Y/%m/')),
                ('transcription', models.TextField(blank=True, help_text='AI transcription of voice recording')),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('specific_users', 'Specific Users'), ('groups', 'Groups'), ('community', 'Community')], default='private', max_length=20)),
                ('dream_date', models.DateField(default=django.utils.timezone.now, help_text='When the dream occurred')),
                ('mood', models.CharField(blank=True, help_text='Emotional tone of the dream', max_length=50)),
                ('lucidity_level', models.IntegerField(default=0, help_text='Lucidity level (0-10)')),
                ('themes', models.JSONField(blank=True, default=list, help_text='AI-identified themes')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='AI-identified symbols')),
                ('entities', models.JSONField(blank=True, default=list, help_text='People, places, objects in the dream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dreams',
                'ordering': ['-dream_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dream_tags',
                'ordering': ['name'],
            },
        ),
    ]
