# Generated by Django 5.2.4 on 2025-07-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0001_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_dreams', to='sharing.dreamgroup'),
        ),
    ]
