# Generated by Django 5.2.4 on 2025-07-27 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_dreams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamtag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamtag',
            name='dreams',
            field=models.ManyToManyField(related_name='tags', to='dreams.dream'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['-dream_date'], name='dreams_dream_d_53bc26_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['user', '-dream_date'], name='dreams_user_id_f2648d_idx'),
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['privacy_level'], name='dreams_privacy_9748a5_idx'),
        ),
    ]
