# Generated by Django 5.2.4 on 2025-08-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image file upload', null=True, upload_to='dream_images/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dreams.dream')),
            ],
            options={
                'db_table': 'dream_images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
