# Generated by Django 5.2.4 on 2025-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_dreamimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='semantic_bits',
            field=models.JSONField(blank=True, default=dict, help_text='Full semantic analysis including all POS tags'),
        ),
        migrations.AddField(
            model_name='dream',
            name='semantic_nouns',
            field=models.JSONField(blank=True, default=list, help_text='Extracted nouns from the description'),
        ),
        migrations.AddField(
            model_name='dream',
            name='semantic_verbs',
            field=models.JSONField(blank=True, default=list, help_text='Extracted verbs from the description'),
        ),
    ]
