# Generated by Django 5.2.4 on 2025-07-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_music',
            field=models.CharField(choices=[('none', 'No Music'), ('ambient_forest', 'Forest Ambience'), ('meditation_bells', 'Meditation Bells'), ('ocean_waves', 'Ocean Waves'), ('rain_sounds', 'Gentle Rain'), ('tibetan_bowls', 'Tibetan Bowls'), ('white_noise', 'White Noise')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Light'), ('night', 'Night Sky'), ('clouds', 'Soft Clouds'), ('twilight', 'Twilight Purple'), ('ocean', 'Deep Ocean'), ('forest', 'Forest Green'), ('cosmic', 'Cosmic Space')], default='default', max_length=50),
        ),
    ]
