# Generated by Django 5.2.4 on 2025-08-16 02:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image file upload', null=True, upload_to='thing_images/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'thing_images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ThingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'thing_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Thing description')),
                ('voice_recording', models.FileField(blank=True, help_text='Voice recording of the thing', null=True, upload_to='thing_recordings/%Y/%m/')),
                ('transcription', models.TextField(blank=True, help_text='AI transcription of voice recording')),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('specific_users', 'Specific Users'), ('groups', 'Groups'), ('community', 'Community')], default='private', max_length=20)),
                ('thing_date', models.DateField(default=django.utils.timezone.now, help_text='When the thing occurred')),
                ('mood', models.CharField(blank=True, help_text='Emotional tone of the thing', max_length=50)),
                ('lucidity_level', models.IntegerField(default=0, help_text='Lucidity level (0-10)')),
                ('themes', models.JSONField(blank=True, default=list, help_text='AI-identified themes')),
                ('symbols', models.JSONField(blank=True, default=list, help_text='AI-identified symbols')),
                ('entities', models.JSONField(blank=True, default=list, help_text='People, places, objects in the thing')),
                ('semantic_verbs', models.JSONField(blank=True, default=list, help_text='Extracted verbs from the description')),
                ('semantic_nouns', models.JSONField(blank=True, default=list, help_text='Extracted nouns from the description')),
                ('semantic_bits', models.JSONField(blank=True, default=dict, help_text='Full semantic analysis including all POS tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with_groups', models.ManyToManyField(blank=True, related_name='shared_things', to='sharing.thinggroup')),
            ],
            options={
                'db_table': 'things',
                'ordering': ['-thing_date', '-created_at'],
            },
        ),
    ]
