# Generated by Django 5.2.4 on 2025-08-16 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_things', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thingimage',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='things.thing'),
        ),
        migrations.AddField(
            model_name='thingtag',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thingtag',
            name='things',
            field=models.ManyToManyField(related_name='tags', to='things.thing'),
        ),
        migrations.AddIndex(
            model_name='thing',
            index=models.Index(fields=['-thing_date'], name='things_thing_d_edcd74_idx'),
        ),
        migrations.AddIndex(
            model_name='thing',
            index=models.Index(fields=['user', '-thing_date'], name='things_user_id_203a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='thing',
            index=models.Index(fields=['privacy_level'], name='things_privacy_ddbe8d_idx'),
        ),
    ]
