# Generated by Django 5.2.4 on 2025-08-17 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Story description or synopsis')),
                ('privacy_level', models.CharField(choices=[('private', 'Private'), ('specific_users', 'Specific Users'), ('groups', 'Groups'), ('community', 'Community')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_count', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Position in the story sequence')),
                ('duration', models.IntegerField(default=5, help_text='Display duration in seconds')),
                ('transition_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('none', 'None')], default='fade', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this thing in the story')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_things', to='things.story')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_stories', to='things.thing')),
            ],
            options={
                'db_table': 'story_things',
                'ordering': ['order', 'added_at'],
                'unique_together': {('story', 'order')},
            },
        ),
        migrations.AddField(
            model_name='story',
            name='things',
            field=models.ManyToManyField(blank=True, related_name='stories', through='things.StoryThing', to='things.thing'),
        ),
    ]
