# Generated by Django 5.2.4 on 2025-07-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('theme', 'Recurring Theme'), ('symbol', 'Recurring Symbol'), ('entity', 'Recurring Entity'), ('emotion', 'Emotional Pattern'), ('sequence', 'Sequential Pattern')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='AI-generated description of the pattern')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in this pattern (0-1)')),
                ('occurrence_count', models.IntegerField(default=0, help_text='Number of dreams containing this pattern')),
                ('first_occurrence', models.DateField(blank=True, help_text='Date of first dream with this pattern', null=True)),
                ('last_occurrence', models.DateField(blank=True, help_text='Date of most recent dream with this pattern', null=True)),
                ('visualization_data', models.JSONField(blank=True, default=dict, help_text='Data for pattern visualization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dream_patterns',
                'ordering': ['-confidence_score', '-occurrence_count'],
            },
        ),
        migrations.CreateModel(
            name='DreamPatternOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, help_text='Specific context of pattern in this dream')),
                ('strength', models.FloatField(default=0.5, help_text='Strength of pattern in this dream (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dream_pattern_occurrences',
            },
        ),
        migrations.CreateModel(
            name='PatternConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_strength', models.FloatField(default=0.0, help_text='Strength of connection (0-1)')),
                ('connection_type', models.CharField(blank=True, help_text='Type of connection', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pattern_connections',
            },
        ),
    ]
