# Generated by Django 5.2.4 on 2025-07-27 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0003_initial'),
        ('patterns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dreampattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreampatternoccurrence',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='dreampatternoccurrence',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.dreampattern'),
        ),
        migrations.AddField(
            model_name='dreampattern',
            name='dreams',
            field=models.ManyToManyField(related_name='patterns', through='patterns.DreamPatternOccurrence', to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='patternconnection',
            name='pattern1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='patterns.dreampattern'),
        ),
        migrations.AddField(
            model_name='patternconnection',
            name='pattern2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='patterns.dreampattern'),
        ),
        migrations.AlterUniqueTogether(
            name='dreampatternoccurrence',
            unique_together={('dream', 'pattern')},
        ),
        migrations.AlterUniqueTogether(
            name='dreampattern',
            unique_together={('user', 'pattern_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='patternconnection',
            unique_together={('pattern1', 'pattern2')},
        ),
    ]
