# Generated by Django 5.2.4 on 2025-08-16 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patterns', '0001_initial'),
        ('things', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thingpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thing_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patternconnection',
            name='pattern1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='patterns.thingpattern'),
        ),
        migrations.AddField(
            model_name='patternconnection',
            name='pattern2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='patterns.thingpattern'),
        ),
        migrations.AddField(
            model_name='thingpatternoccurrence',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.thingpattern'),
        ),
        migrations.AddField(
            model_name='thingpatternoccurrence',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.thing'),
        ),
        migrations.AddField(
            model_name='thingpattern',
            name='things',
            field=models.ManyToManyField(related_name='patterns', through='patterns.ThingPatternOccurrence', to='things.thing'),
        ),
        migrations.AlterUniqueTogether(
            name='patternconnection',
            unique_together={('pattern1', 'pattern2')},
        ),
        migrations.AlterUniqueTogether(
            name='thingpatternoccurrence',
            unique_together={('thing', 'pattern')},
        ),
        migrations.AlterUniqueTogether(
            name='thingpattern',
            unique_together={('user', 'pattern_type', 'name')},
        ),
    ]
