# Generated by Django 5.2.4 on 2025-07-27 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0003_initial'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.dreamgroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamgroup',
            name='members',
            field=models.ManyToManyField(related_name='dream_groups', through='sharing.GroupMembership', through_fields=('group', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='affected_groups',
            field=models.ManyToManyField(blank=True, related_name='share_notifications', to='sharing.dreamgroup'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='affected_users',
            field=models.ManyToManyField(blank=True, related_name='share_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_history', to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='sharehistory',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
    ]
